from django.conf.urls import url, include
from django.urls import path, re_path
from django.contrib import admin

from rest_framework import routers
from posts import views

# this is DRF router for REST API viewsets
router = routers.DefaultRouter()

# register REST API endpoints with DRF router
router.register(r'posts', views.PostViewSet)
router.register(r'hashtags', views.HashtagViewSet) #necesario?
# router.register(r'users', views.UserViewSet)
# router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    # default django admin interface
    #url(r'^admin/', include(admin.site.urls)),
    path('admin/', admin.site.urls),

    # REST API root view (generated by DRF router)
    # url(r'^api/', include(router.urls, namespace='api')),
    url(r'^', include(router.urls)),

    # pure django views that don't use DRF
    # url(r'^$', index_view, {}, name='index'),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))

    # ni idea que es esto \/
    # re_path('api/(?P<version>(v1|v2))/', include('posts.urls'))
]
